# Generated by Django 4.2.5 on 2023-09-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="department",
            field=models.CharField(
                choices=[
                    ("teeth_whiteing", "Teeth Whiteing"),
                    ("teeth_cleaning", "Teeth Cleaning"),
                    ("quality_brackets", "Quality Brackets"),
                    ("modern_anesthetic", "Modern Anesthetic"),
                ],
                max_length=100,
            ),
        ),
    ]
