# Generated by Django 4.2.5 on 2023-09-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_alter_appointment_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctor",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="google_plus",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="proficiency",
            field=models.CharField(
                choices=[
                    ("dentist", "Dentist"),
                    ("doctor", "Doctor"),
                    ("nurse", "Nurse"),
                    ("therapist", "Therapist"),
                    ("system_analyst", "System Analyst"),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctor",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
    ]
