# Generated by Django 4.2.5 on 2023-09-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0003_doctor_description_doctor_facebook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
