# Generated by Django 4.2.5 on 2023-10-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0006_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="from_page",
            field=models.CharField(
                blank=True,
                choices=[("home", "Home"), ("contact", "Contact")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="website",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
